frontend:
  - changed-files:
    - any-glob-to-any-file: 'frontend/**/*'
backend:
  - changed-files:
    - any-glob-to-any-file: 'server/**/*'
cli:
  - changed-files:
    - any-glob-to-any-file: 'cli/**/*'
docs:
  - changed-files:
    - any-glob-to-any-file: '*.md'
ci:
  - changed-files:
    - any-glob-to-any-file: '.github/**/*'
deploy:
  - changed-files:
    - any-glob-to-any-file: 'deploy/**/*'
